### PR TITLE
[REF] Adding pep8 to projects

### PR DESCRIPTION
**Pull request by KarenKawaii**

### CODE REVIEW

**Comment by KarenKawaii** [comment]
rgrep command output: clear

**Comment by KarenKawaii** [comment]
@dsabrinarg  @moylop260 
The test server failed. But the other tests are green.

**Comment by moylop260** [comment]
@KarenKawaii 
Can you update your branch?
I fixed this error

**Comment by KarenKawaii** [comment]
It's green now.

**Comment by KarenKawaii** [comment]
Rebase done @moylop260

**Pull request merged**
