### PR TITLE
8.0 odoo panama yoytec issue 545 dev luisllave

### PR DESCRIPTION
**Pull request by luisll-vauxoo**
Only remove the lines which assign a default value to vat_country_id field; then this field is blank in the GUI, and don't run the check about RUC.

### CODE REVIEW

**Comment by moylop260** [comment]
:-1:
Se aplicó un: "Si marca error, elimínalo"

**Comment by luistorresm** [comment]
Dummy PR https://github.com/Vauxoo/yoytec/pull/639

**Comment by luistorresm** [comment]
@moylop260 

You could check this PR?

Regards

**Comment by moylop260** [comment]
LGTM

Just a small fix...

translation2

**Pull request merged**
