### PR TITLE
l10n_pa_localization, vat_partitioned: Move vat field from page Accounting to address section of res_partner

### PR DESCRIPTION
**Pull request by ysantiago**
[TASK#5682](https://www.vauxoo.com/web#id=5682&view_type=form&model=project.task&menu_id=136&action=138)

### CODE REVIEW

**Comment by moylop260** [comment]
@nhomar
A replace of view could make us errors in other inherited views.
What do you think about use a extra related field?

NOTE: I don't know if a sequence very high could be the work.

**Comment by ysantiago** [comment]
@JulioSerna here the changes, your opinion is important.

**Comment by JulioSerna** [comment]
if we are continue working with the `address_format` concept is the way that we can modify the part of view [address_format](https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/res/res_partner_view.xml#L168)

in fact, it is the current behavior in Odoo, the address_format is render by the [address_format of the company](https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/res/res_partner.py#L63:#L79) and then if you can modify this section of view you need to modify by code python because with inhertit view xml does not work

**Comment by ysantiago** [comment]
@moylop260 
This is the way we can add this field in that part of the view because it doesn't work with inherit view

**Comment by moylop260** [comment]
We should let the project of localisation as clean as posible.
If you require a `position="replace"` to satisfied a customer request then you should use the customer project.
And we could avoid errors of other project that use odoo-panama with `...<xpath expr="//field[@name='vat']" position="after">  <field name="my_new_field"/>...` because your `<xpath expr="//field[@name='vat']" position="replace">` deletes the field and won't found it.

**Comment by ysantiago** [comment]
The error occurs if the view with `...<xpath expr="//field[@name='vat']" position="after"> <field name="new_field"/>...` has a priority equal or lower than view with `...<xpath expr="//field[@name='vat']" position="replace">`. 

Therefore, it is assigned a low priority to the view that makes the replace: [res_partner_view.xml](https://github.com/Vauxoo/odoo-panama/pull/35/commits/eb32b75039ba66ab6c8e63ad56142bcbd37ea311#diff-ec5d06001ce094466a7e781a434ccb94R8)

**Comment by ysantiago** [comment]
Hello @moylop260 

The place where the VAT field is going to move is pending to be defined, this PR can be closed.

**Comment by gquilarque** [comment]
Hi, 

@ysantiago and @moylop260 this feature will by solve by @josemoralesp in this Task#5700, Point#5

@josemoralesp you can review this PR for check the proposed changes by @ysantiago and the comments made by @moylop260 

Thanks @ysantiago and @moylop260 for your support. 🎱

**Pull request closed without merging**
