### PR TITLE
[IMP][l10n_pa_localization]Changed address format when country is Panama

### PR DESCRIPTION
**Pull request by luistorresm**

### CODE REVIEW

**Comment by moylop260** [comment]
Could you add unitest?

**Comment by luistorresm** [comment]
Done @moylop260 ,

Can you check please.

**Comment by moylop260** [comment]
Could you make dummy pr?

**Comment by luistorresm** [comment]
https://github.com/Vauxoo/yoytec/pull/400

**Comment by luistorresm** [comment]
To solve https://github.com/Vauxoo/yoytec/issues/364

**Pull request merged**
